resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: jtarchie/pr

resources:
  - name: git-demo-react-repo
    type: git
    source:
      uri: git@github.com:Tribalscale/demo-react-repo
      branch: develop
      private_key: ((github-private-key))
  - name: cf-dev
    type: cf
    source:
      api: https://api.run.pivotal.io
      username: ((cf-username))
      password: ((cf-password))
      organization: ((cf-org))
      space: ((cf-dev-space))
  - name: cf-acceptance
    type: cf
    source:
      api: https://api.run.pivotal.io
      username: ((cf-username))
      password: ((cf-password))
      organization: ((cf-org))
      space: ((cf-acceptance-space))
  - name: git-pr-demo-react
    type: pull-request
    source:
      access_token: ((github-access-token))
      private_key: ((github-private-key))
      uri: git@github.com:TribalScale/demo-react-repo
      repo: TribalScale/demo-react-repo
      base: develop


jobs:
  - name: test-demo-react
    plan:
      - get: git-demo-react-repo
        trigger: true
      - task: test
        input_mapping:
          demo-react-repo: git-demo-react-repo
        file: git-demo-react-repo/test.yml
        params:
          NODE_ENV: test

  - name: deploy-cf-demo-react
    plan:
      - get: git-demo-react-repo
        trigger: true
        passed: [test-demo-react]
      - task: build
        input_mapping:
          demo-react-repo: git-demo-react-repo
        file: git-demo-react-repo/build.yml
        params:
          MANIFEST: manifest_dev.yml
          PUBLIC_URL: /
          REACT_APP_GA: UA-32916794-3
      - put: cf-dev
        params:
          manifest: build/manifest_dev.yml
          path: build
          current_app_name: demo-react

  - name: deploy-cf-acceptance-demo-react
    plan:
      - get: git-demo-react-repo
        passed: [test-demo-react, deploy-cf-demo-react]
      - task: build
        input_mapping:
          demo-react-repo: git-demo-react-repo
        file: git-demo-react-repo/build.yml
        params:
          MANIFEST: manifest_dev.yml
          PUBLIC_URL: /
          REACT_APP_GA: UA-32916794-4
      - put: cf-acceptance
        params:
          manifest: build/manifest_dev.yml
          path: build
          current_app_name: acceptance-demo-react
  - name: test-web-pr
    plan:
      - get: git-pr-demo-react
        trigger: true
      - task: test
        input_mapping:
          demo-react-repo: git-pr-demo-react
        file: git-pr-demo-react/test.yml
        params:
          NODE_ENV: test
        on_success:
          put: git-pr-demo-react
          params:
            path: git-pr-demo-react
            status: success
        on_failure:
          put: git-pr-demo-react
          params:
            path: git-pr-demo-react
            status: failure
